package nl.eldude.rmd.drooling.rules;

import nl.eldude.rnd.drooling.data.CustomerType;
import nl.eldude.rnd.drooling.model.Item;
import nl.eldude.rnd.drooling.model.LineItem;
import nl.eldude.rnd.drooling.model.Customer;
import nl.eldude.rnd.drooling.model.Order
import java.util.List

global nl.eldude.rnd.drooling.model.Order order;
dialect  "mvel";

rule "Club discount 10%"
    when
        Customer(customerType == CustomerType.CLUB);
        lineItem: LineItem(order.getLineItems())
    then
        modify(lineItem)
        {
            setDiscount(10)
        }
end;
