package nl.eldude.rnd.drooling.rules;
dialect  "mvel";

import nl.eldude.rnd.drooling.model.Item;
import nl.eldude.rnd.drooling.model.LineItem;
import nl.eldude.rnd.drooling.data.CustomerType
import nl.eldude.rnd.drooling.model.Order
import java.util.List

rule "Club discount 10%"
    when
        customerType: CustomerType(customerType==CustomerType.CLUB);
        order: Order(lineItems)
        lineItem: LineItem(order.getLineItems())
    then
        modify(lineItem)
        {
            setDiscount(10)
        }
end;
